#!/usr/bin/env python

import sys
import json
import time
from warnings import warn

from web3 import Web3, HTTPProvider

LOCAL_NODE = 'http://localhost:8545'

def main(owner1, owner2, owner3):
    contract_json = json.load(open('./build/contracts/TrezorMultisig2of3.json'))
    w3 = Web3(HTTPProvider(LOCAL_NODE, request_kwargs={'timeout': 60}))
    contract = w3.eth.contract(abi=contract_json['abi'], bytecode=contract_json['bytecode'])
    warn("Authorize Transaction Creating Contract, probably in a browser window")
    tx_hash = contract.deploy(transaction={'from': w3.eth.accounts[0], 'gas': 1100000},
                              args = [owner1, owner2, owner3])
    time.sleep(10)
    tx_receipt = w3.eth.getTransactionReceipt(tx_hash)
    contract_address = tx_receipt['contractAddress']
    print(contract_address)
    

if __name__ == '__main__':
    if (len(sys.argv) < 4):
        sys.exit("USAGE: create_ethereum_multisig OWNER_ADDRESS_1 OWNER_ADDRESS_2 OWNER_ADDRESS_3")
    main(sys.argv[1], sys.argv[2], sys.argv[3])
