#!/usr/bin/env python

import sys  

from trezorlib.client import TrezorClient
from trezorlib.device import TrezorDevice

def main(message,path):
    # List all connected TREZORs on USB
    devices = TrezorDevice.enumerate()

    # Check whether we found any
    if len(devices) == 0:
        sys.exit('No TREZOR found')

    # Use first connected device
    transport = devices[0]

    # Creates object for manipulating TREZOR
    client = TrezorClient(transport)

    bip32_path = client.expand_path(path)
    
    sig = client.ethereum_sign_message(bip32_path,message.lower())
    # Parse sig for r,s,v
    print(sig.signature.hex())

    client.close()

if __name__ == '__main__':
    if (len(sys.argv) < 3):
        sys.exit("USAGE: export_ethereum_spend_signature MESSAGE BIP32_PATH")
    main(sys.argv[1],sys.argv[2])
