#!/usr/bin/env python

import sys  

from trezorlib.client import TrezorClient
from trezorlib.device import TrezorDevice

def main(path):
    # List all connected TREZORs on USB
    devices = TrezorDevice.enumerate()

    # Check whether we found any
    if len(devices) == 0:
        sys.exit('No TREZOR found')

    # Use first connected device
    transport = devices[0]

    # Creates object for manipulating TREZOR
    client = TrezorClient(transport)

    bip32_path = client.expand_path(path)
    
    address = client.ethereum_get_address(bip32_path, True)
    print("0x"+address.hex())

    client.close()

if __name__ == '__main__':
    if (len(sys.argv) < 2):
        sys.exit("USAGE: export_ethereum_address BIP32_PATH")
    main(sys.argv[1])
