#!/usr/bin/env python

import sys

def parse_signature(signature):
    R = "0x" + signature[:64]
    S = "0x" + signature[64:128]
    V_tmp = signature[128:]
    if (V_tmp == "1b"):
        V = "0x00"
    elif (V_tmp == "1c"):
        V = "0x01"
    else:
        V = "crap"
    return [R, S, V]
    

if __name__ == '__main__':
    if (len(sys.argv) < 2):
        sys.exit("USAGE: parse_spend_signature SIGNATURE")
    print(parse_signature(sys.argv[1]))
